SELECT 
    employee_id, 
    DATEADD(MONTH, 15, DATEADD(DAY, 15,  joindate)) AS BonusEligibilityDate,
    DATEDIFF(YEAR, DOB, DATEADD(MONTH, 15, DATEADD(DAY, 15,  joindate))) AS AgeInYears,
    DATEDIFF(MONTH, DOB, DATEADD(MONTH, 15, DATEADD(DAY, 15,  joindate))) % 12 AS AgeInMonths,
    DATEDIFF(DAY, DATEADD(MONTH, DATEDIFF(MONTH, DOB, DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate))), DOB), DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate))) AS AgeInDays,
    DATENAME(WEEKDAY, DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate))) AS WeekdayName,
    DATEPART(WEEK, DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate))) AS WeekOfYear,
    DATEPART(DAYOFYEAR, DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate))) AS DayOfYear,
    DATEPART(WEEKDAY, DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate))) - DATEPART(WEEKDAY, DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate)) - DATEPART(DAY, DATEADD(MONTH, 15, DATEADD(DAY, 15, joindate))) + 1) / 7 + 1 AS WeekOfMonth
FROM 
    Employee_bonus_table
WHERE 
    DATEDIFF(DAY, joindate, GETDATE()) >=472